// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GoogleTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        driver.get("https://www.google.by/");
        driver.manage().window().setSize(new Dimension(1200, 781));
    }

    @Test
    public void GoogleSearch() {

        driver.findElement(By.name("q")).click();
        driver.findElement(By.name("q")).sendKeys("Привет, мир");
        driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
        {
            WebElement element = driver.findElement(By.xpath("//h3[contains(.,\'Привет, Мир!\')]"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.id("rcnt")).click();
        driver.findElement(By.xpath("//span[contains(.,\'Весь «Мир» в вашем смартфоне — скачайте приложение «Привет, Мир!» и наслаждайтесь выгодными покупками с кешбэком и скидками! • Установите приложение.\')]")).click();
        driver.findElement(By.xpath("//form[@id=\'tsf\']/div/div/div[2]/div/div")).click();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
}
